services:
  backend:
    build:
      context: .
      dockerfile: ./docker_files/backend.Dockerfile
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    volumes:
      - ./client_backend:/app:rw
    restart: always
  frontend:
    build:
      context: .
      dockerfile: ./docker_files/frontend.Dockerfile
    ports:
      - 3000:3000
    command: npm start
    env_file:
      - .env
    restart: always
    # volumes:
    #   - ./vocode_react_demo:/app:rw
